### ISSUE TITLE
Fails to run under CentOS 6 with Python 2.7.17 (Anaconda)

### ISSUE THREAD

**Issue by Znuff** [JonathonReinhart/staticx#110]
While CentOS 6 is on the way of EOL, this could potentially still be investigated.

I suspect this is because of a very old `lzma` version:
```
Traceback (most recent call last):
  File "/root/miniconda2/bin/staticx", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda2/lib/python2.7/site-packages/staticx/__main__.py", line 59, in main
    debug = args.debug,
  File "/root/miniconda2/lib/python2.7/site-packages/staticx/api.py", line 141, in generate
    with generate_archive(prog, tmpprog, orig_interp, tmpdir, libs, strip=strip, compress=compress) as ar:
  File "/root/miniconda2/lib/python2.7/site-packages/staticx/api.py", line 62, in generate_archive
    run_hooks(ar, orig_prog)
  File "/root/miniconda2/lib/python2.7/site-packages/staticx/archive.py", line 71, in __exit__
    self.tar.close()
  File "/root/miniconda2/lib/python2.7/tarfile.py", line 1810, in close
    self.fileobj.write(NUL * (BLOCKSIZE * 2))
  File "/root/miniconda2/lib/python2.7/site-packages/backports/lzma/__init__.py", line 331, in write
    compressed = self._compressor.compress(data)
_lzma.LZMAError: Internal error
```

```
# lzma --version
xz (XZ Utils) 4.999.9beta
liblzma 4.999.9beta
```

What seems to work is to install `backports.lzma` via `conda`:

```
# conda install -c conda-forge backports.lzma
```

Then installing `staticx` via `pip`.

This is more of a `backports.lzma` issue for Python 2.7, but I hope it saves some poor soul who ends up searching for this.

**Comment by JonathonReinhart** [comment]
@Znuff To be clear: this is not a problem with staticx, correct? I'm going to close this issue since there is nothing for me to do here. It should still be accessible for those who might search for this error in the future. Thanks.

**Comment by Znuff** [comment]
While there is nothing you can directly do with in this case, there could be a scenario where you could:

1. Handle the Exception and provide a more meaningful error message [and...]
2. Maybe use gzip/bzip2 instead of lzma in the case of lzma error?

But even in that case, I think that the tar module is probably a better place to handle the lzma exception.
