### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 80: ordinal not in range(128)

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#147]
I encountered this while running under Docker (`i386/ubuntu:16.04` with additional packages):
```
Traceback (most recent call last):
  File "/home/jreinhart/.local/bin/staticx", line 8, in <module>
    sys.exit(main())
  File "/home/jreinhart/.local/lib/python3.5/site-packages/staticx/__main__.py", line 55, in main
    debug = args.debug,
  File "/home/jreinhart/.local/lib/python3.5/site-packages/staticx/api.py", line 128, in generate
    force_rpath=True, no_default_lib=True)
  File "/home/jreinhart/.local/lib/python3.5/site-packages/staticx/elf.py", line 194, in patch_elf
    tool_patchelf.run_check(*args)
  File "/home/jreinhart/.local/lib/python3.5/site-packages/staticx/elf.py", line 57, in run_check
    rc, stdout = self.run(*args, **kw)
  File "/home/jreinhart/.local/lib/python3.5/site-packages/staticx/elf.py", line 43, in run
    **kw)
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1757, in _communicate
    self.stderr.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 976, in _translate_newlines
    data = data.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 80: ordinal not in range(128)
```

**Comment by JonathonReinhart** [comment]
I encountered this while running i 

It turns out this happens when running in a non-UTF8 locale:
```
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

I removed the `universal_newlines = True` from the `subprocess.run()` invocation and logged stdout and stderr before manually decoding, and saw this:
```
Standard error: b'warning: working around a Linux kernel bug by creating a hole of 12288 bytes in \xe2\x80\x98/tmp/staticx-prog-9chj___b\xe2\x80\x99\n'
```

The problem is with `patchelf`: They use UTF-8 characters in their string literals here:
https://github.com/NixOS/patchelf/blob/0.9/src/patchelf.cc#L617
