### ISSUE TITLE
Error during scons build: ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#155]
Running `pip install staticx...tar.gz` on a system where SCons is Python 2, and Python 2 environment does *not* have pip, etc. and therefore no `pkg_resources`:
```
  running bdist_wheel
  running build
  running build_bootloader
  ImportError: No module named pkg_resources:
    File "/tmp/pip-req-build-084w3ljx/SConstruct", line 67:
      env.InstallAs('#staticx/assets/$MODE/bootloader', env.BuildSubdir('bootloader'))
    File "/usr/lib/scons/SCons/Environment.py", line 224:
      return self.method(*nargs, **kwargs)
    File "/tmp/pip-req-build-084w3ljx/SConstruct", line 47:
      exports = dict(env=env.Clone()),
    File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
      return _SConscript(self.fs, *files, **subst_kw)
    File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
      exec _file_ in call_stack[-1].globals
    File "/tmp/pip-req-build-084w3ljx/bootloader/SConscript", line 7:
      from dynversion import get_dynamic_version
    File "/tmp/pip-req-build-084w3ljx/dynversion.py", line 2:
      import staticx.version
    File "/tmp/pip-req-build-084w3ljx/staticx/version.py", line 71:
      __version__ = get_version()
    File "/tmp/pip-req-build-084w3ljx/staticx/version.py", line 59:
      import pkg_resources
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-084w3ljx/setup.py", line 158, in <module>
      'bdist_wheel':      bdist_wheel_hook,
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-084w3ljx/setup.py", line 31, in run
      self.run_command('build_bootloader')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-084w3ljx/setup.py", line 26, in run
      check_call(['scons', '-Q'])
    File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['scons', '-Q']' returned non-zero exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for staticx
```

This happens because:
- `setup.py` hooks the `build` class to build the bootloader by invoking `scons`
- `dynversion.py` essentially wraps `staticx.version.get_version()`
- `get_version()` imports `pkg_resources`

This highlights a core problem: Do we really want to require SCons python environment to be compatible with our now Python-3-only `staticx.version`?

In #115 I dropped support for Python 2.7, but didn't pay attention to the fact that Scons is often py27, and is importing staticx (now py3 only) code. This is not a big deal by itself; `dynversion.py` and `staticx/version.py` are minimal and can stay 2/3 bilingual. But that means that Scons Python must also have `pkg_resources`.

It feels `setup.py` should only be concerned with the Python environment that invoked it.

So what's the best way for SCons to get the version?
1. `SConstruct` **imports** it like it does now, and fails if `pkg_resources` is missing.
2. `SConstruct` **executes** `dynversion.py` in a `python3` subprocess (WIP #156) 
    - Con: is `python3` always the right python?
    - PR: #156
3. `setup.py` **passes** the staticx version to Scons
    - Con: it won't be set during manual scons dev invocation
    - PR: #157

**Comment by JonathonReinhart** [comment]
As you know staticx setup.py hooks the build class to build the bootloader by invoking Scons.

I have a top-level dynversion.py whose get_version() basically just returns staticx.version.get_version(), which looks at git, pkg_resources, etc to determine the staticx version. dynversion.py is used by setup.py, of course.

Currently, SConscript also imports dynversion.py to embed that version in the bootloader binary.

At some point I dropped support for Python 2.7, but didn't pay attention to the fact that Scons is often py27, and is importing staticx (now py3 only) code. Not a big deal. But that means that Scons Python must also have pkg_resources.

It feels like my setup.py should only be concerned with the Python that invoked it.

So what's the best way for Scons to get the version?
1. Importing it like it does now, and failing if pkg_resources is missing.
2. SCons runs dynversion.py in a python3 subprocess (have this working now) -- con: is "python3" always the right python?
3. setup.py must pass staticx version to Scons -- con: it won't be set during manual scons dev invocation
