### ISSUE TITLE
Errors in alpine, when converting a pyinstaller binary

### ISSUE THREAD

**Issue by aptalca** [JonathonReinhart/staticx#166]
Hi,
I have a pyinstaller built binary, built on alpine 3.12 (musl) and I'm trying to convert it to fully static via staticx.
I installed the dependencies, binutils, patchelf and scons.

When I run staticx with DEBUG on, I get the following output:
```
DEBUG:root:Running ['patchelf', '--set-interpreter', 'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', '--set-rpath', 'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr', '--force-rpath', '/tmp/staticx-prog-ddmbkzn_']
DEBUG:root:Running ['patchelf', '--no-default-lib', '/tmp/staticx-prog-ddmbkzn_']
INFO:root:Program interpreter: /lib/ld-musl-x86_64.so.1
INFO:root:Using XZ BCJ filter FILTER_X86
Traceback (most recent call last):
  File "/usr/bin/staticx", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/staticx/__main__.py", line 51, in main
    generate(args.prog, args.output,
  File "/usr/lib/python3.8/site-packages/staticx/api.py", line 136, in generate
    with generate_archive(prog, tmpprog, orig_interp, tmpdir, libs,
  File "/usr/lib/python3.8/site-packages/staticx/api.py", line 42, in generate_archive
    run_hooks(
  File "/usr/lib/python3.8/site-packages/staticx/hooks/__init__.py", line 18, in run_hooks
    hook(ctx)
  File "/usr/lib/python3.8/site-packages/staticx/hooks/glibc.py", line 10, in process_glibc_prog
    if not is_linked_against_glibc(ctx.orig_prog):
  File "/usr/lib/python3.8/site-packages/staticx/hooks/glibc.py", line 40, in is_linked_against_glibc
    for verneed, vernaux_iter in sec.iter_versions():
AttributeError: 'KeyError' object has no attribute 'iter_versions'
```

The ldd output of my binary is:
```
        /lib/ld-musl-x86_64.so.1 (0x149a35546000)
        libz.so.1 => /lib/libz.so.1 (0x149a35512000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x149a35546000)
```

Any ideas?

Thanks

PS. I forgot to mention that I tried both the latest stable version 0.12 as well as locally built master branch

**Comment by aptalca** [comment]
looks like pyinstaller is crapping out prior. I need to look into it a little more. Closing for now.
